<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite guice-stage="DEVELOPMENT" name="Failed suite [Suite]">
  <test thread-count="5" name="Test(failed)" parallel="classes">
    <classes>
      <class name="tests.rest.TC001_GetCustomers">
        <methods>
          <include name="beforeClass"/>
          <include name="beforeSuite"/>
          <include name="afterSuite"/>
          <include name="setValues"/>
          <include name="getCustomers"/>
          <include name="beforeMethod"/>
          <include name="afterMethod"/>
        </methods>
      </class> <!-- tests.rest.TC001_GetCustomers -->
      <class name="tests.rest.TC006_ValidateCustomers_AfterInsert">
        <methods>
          <include name="setValues"/>
          <include name="beforeClass"/>
          <include name="beforeSuite"/>
          <include name="afterSuite"/>
          <include name="beforeMethod"/>
          <include name="getCustomers"/>
          <include name="afterMethod"/>
        </methods>
      </class> <!-- tests.rest.TC006_ValidateCustomers_AfterInsert -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
